### ISSUE TITLE
Cannot get same results for the telescope plugin

### ISSUE THREAD

**Issue by skoch13** [natecraddock/telescope-zf-native.nvim#11]
First of all, thank you for the zf project. I really like it!

The issue I'm facing is that I can't seem to get the same results for the Telescope plugin when searching with an additional space-delimited token. Here are the screenshots I took with ZF (`git ls-files` and `fd`) and Telescope:

![fd](https://github.com/natecraddock/telescope-zf-native.nvim/assets/29177689/2a150ee1-6574-4148-868d-9febab2a44ae)
![git ls](https://github.com/natecraddock/telescope-zf-native.nvim/assets/29177689/a3486b3d-8a97-4161-ac6c-9f2a5379f026)
![telescope](https://github.com/natecraddock/telescope-zf-native.nvim/assets/29177689/02cc6e4f-752b-4e9b-b865-2db1f1515f5b)

MacOS 14.3
nvim 0.9.5

```
zf-native: require("zf-native.health").check()

Installation ~
- libzf library path: .../lib/libzf-osx-arm64.so
- OK libzf path is valid

Configuration
  - zf telescope file sorter enabled
    - highlights: true
    - filename score priority: true
  - zf telescope generic sorter enabled
    - highlights: true
    - filename score priority: false ~
```

Picker settings:

```
        pickers = {
          find_files = {
            theme = "dropdown",
            find_command = {
              "fd",
              "--type",
              "f",
              "--color=never",
              "--hidden",
              "--follow",
              "-E",
              ".git/*",
            },
```

Thank you in advance

**Comment by skoch13** [comment]
Looks like the mixture of my other settings is preventing it from working as desired. I'll re-examine them.

**Comment by natecraddock** [comment]
Glad you got it working!

> First of all, thank you for the zf project. I really like it!

Thanks 😄

**Comment by skoch13** [comment]
I _finally_ found the root cause: telescope's `path_display` option might mess with the results, see the similar issue https://github.com/nvim-telescope/telescope.nvim/issues/2360

**Comment by natecraddock** [comment]
Interesting. I hope the telescope devs can figure it out!
