### ISSUE TITLE
FR: Initial sorting when the query is empty

### ISSUE THREAD

**Issue by chrisgrieser** [natecraddock/telescope-zf-native.nvim#12]
Thanks for this sorter, it's definitely an improvement which definitely deserves to be more popular.

---

So one issue I have is the *initial* sorting of results. It seems that when the query is empty, this sorter just passes the results from `fd` through without any sorting.

<img alt="Showcase" width=50% src="https://github.com/nvim-telescope/telescope.nvim/assets/73286100/eceb3523-f024-40f0-9877-c9a640bba7c9">

This initial order is often not desirable, as this results for example in `Makefile` and `README`  always being placed at the top, even though they are files that are rarely accessed in comparison to other files.

One reasonable solution would be to sort specific files further to the top, e.g. prioritizing lua, js, py files over md and Makefiles. Since there are probably quite diverse preferences for initial sorting, it might also make sense to offer an option for an initial-sorting-function, working similarly to telescope's `tiebreaker`.

For reference and more details, see also the issue I opened at the telescope repo: https://github.com/nvim-telescope/telescope.nvim/issues/2905

**Comment by natecraddock** [comment]
Hi!

> Thanks for this sorter, it's definitely an improvement which definitely deserves to be more popular.

Thank you :)

I read through the thread on the telescope.nvim repo, and I think everything you are saying makes sense to me.

I am open to adding an `initial_sort` function, that by default does nothing. This sounds really easy actually. Can you help me make sure I understand everything?

* only triggers when the query is empty
* the function is passed the line
* the function return a float between 0 and 1 for ranking

If that all is correct, this should be a trivial feature to add

**Comment by chrisgrieser** [comment]
great :)

> only triggers when the query is empty

Yep.

> the function is passed the line
> the function return a float between 0 and 1 for ranking

I think for consistency reasons, the sorting function should have the same signature as [telescope's tiebreak function](https://github.com/nvim-telescope/telescope.nvim/blob/7b5c5f56a21e82fdcfe5b250278b8dfc4b1cbab4/doc/telescope.txt#L608-L620), meaning it takes two telescope entry-tables (which have the filepath in `.ordinal`) and returns a boolean. From the telescope docs:

> tiebreak:
> A function that determines how to break a tie when two entries have the same score. Having a function that always returns false would keep the entries in the order they are found, so`existing_entry` before`current_entry`. Vice versa always returning true would place the`current_entry` before the`existing_entry`.
>
> Signature: `function(current_entry, existing_entry, prompt) -> boolean`

Just as an example, this is the function which I am currently using as a tiebreaker, and which I would also use for initial sorting:
```lua
-- prioritze lua/js/ts/py files over other files, then prioritize files with shorter path
local function prioritzeScriptFiles(current_entry, existing_entry, _prompt)
	local priorityExt = { "lua", "js", "ts", "py" }
	current_entry.ext = current_entry.ordinal:match("%w+$")
	existing_entry.ext = existing_entry.ordinal:match("%w+$")
	current_entry.hasPrio = vim.tbl_contains(priorityExt, current_entry.ext)
	existing_entry.hasPrio = vim.tbl_contains(priorityExt, existing_entry.ext)
	if current_entry.hasPrio and not existing_entry.hasPrio then return true end
	return #current_entry.ordinal < #existing_entry.ordinal
end
```

edit:

thinking about it, the scoring approach might actually be smarter to describe sorting. (e.g. giving different filetypes different scores), so I think your suggestions might be better after all 🤔

**Comment by natecraddock** [comment]
> thinking about it, the scoring approach might actually be smarter to describe sorting. (e.g. giving different filetypes different scores), so I think your suggestions might be better after all 🤔

I was going to suggest just that.

I think the core issue here is that the tiebreak logic makes sense when comparing two lines. But at the point where I can add this initial_sort function, it would only have access to one line.

So you would need something like this simplified example

```lua
function initial_sort(line)
    if line:match('.lua$') then
        return 1
    end
    return 0
end
```

And as you say, you could give different file types priority based on the returned score.

If that all sounds good, I can work on adding this soon

**Comment by chrisgrieser** [comment]
Yep, sounds all good! :)

**Comment by natecraddock** [comment]
I just pushed a commit to a branch (https://github.com/natecraddock/telescope-zf-native.nvim/tree/initial-sort) that should implement this. The readme is updated in the branch with documentation.

I tested it and it seemed to work great for me, so let me know how it goes and I'll get it merged in!

**Comment by chrisgrieser** [comment]
Works fine on my end! Using this right now:

```lua
initial_sort = function(path)
	local extensionPrios = { -- 0-1, 0 is highest priority
		lua = 0,
		py = 0.1,
		js = 0.1,
		ts = 0.1,
		sh = 0.5,
		md = 0.9,
	}
	local ext = path:match("%w+$")
	for ft, prio in pairs(extensionPrios) do
		if ext == ft then return prio end
	end
	return 1
end,
```

**Comment by natecraddock** [comment]
Great! Just merged

**Comment by chrisgrieser** [comment]
Thank you for the implementation!
