### ISSUE TITLE
Feature: allow case sensitive setting

### ISSUE THREAD

**Issue by sQVe** [natecraddock/telescope-zf-native.nvim#16]
Hey. 👋

I've been using this sorter for quite some time, and been very happy with it. Lately, I have been wanting to turn off the default smart casing though.

Would it be possible to add an option to enforce the result to be case sensitive?

All the best!

**Comment by natecraddock** [comment]
I agree this would be good, and also easy to add.

@NTBBloodbath I see you added a 👍, are you intending to work on this? I can totally do it this weekend if not!

And thank you @sQVe for the kind words! I love to hear that this is useful for others :)

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath I see you added a 👍, are you intending to work on this? I can totally do it this weekend if not!

Oh, I added the reaction because I would also be interested in that feature. I haven't used Zig in a while so I'm super rusty with it (and next week is exams at the uni) 😅

**Comment by natecraddock** [comment]
Got it! I'll plan on working on this over the weekend. Should be easy

**Comment by natecraddock** [comment]
Hey @sQVe! I just pushed a commit that adds a smart_case option that defaults to true. If you set it to false you should get the behavior you want. Let me know if there is anything else to do!

**Comment by sQVe** [comment]
@natecraddock Cheers for the quick fix! I'll close the issue and reopen if I notice any issues.
