### ISSUE TITLE
Package for LuaRocks

### ISSUE THREAD

**Issue by sahinf** [natecraddock/telescope-zf-native.nvim#18]
Hi, 

Would you consider packaging this nvim plugin to [LuaRocks](https://luarocks.org/) so that the package manager [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) can detect it?
The `rocks.nvim` team [prepared a github action](https://github.com/nvim-neorocks/luarocks-tag-release) that automates this process.

**Comment by NTBBloodbath** [comment]
Hey there!

I'm actually part of the neorocks team and I've been thinking about the same thing as I cannot live without `zf` anymore, however I have some doubts about how embedded `zf` libraries in the `lib` directory would be handled in the rockspec, although I think it should be handled with the `build.install.lib` table. I'll experiment a little with it locally during the weekend and I'll upload the results once everything is fine, if that's okay :)

**Comment by natecraddock** [comment]
Looks like it worked! https://luarocks.org/modules/NTBBloodbath/telescope-zf-native.nvim
