### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/telescope-zf-native.nvim#8]
Hi! I hope you are all doing well!

I no longer use Neovim regularly, but I really would like to keep this plugin alive. It's been really simple to maintain, but I worry about the long-term.

So I'm looking for someone willing to step in and maintain this plugin. Either
1. Someone who is willing to fork and create the new official project or
2. Someone who wants to co-maintain the project

I think the second is the simplest, and no one has to update their configs to point to a new repository.

**If no one steps up, I will try my best to make sure this works for as long as possible.** But I won't make any promises. If a future Neovim release would cause an unreasonable amount of work for me to update this plugin, I probably wouldn't update it.

Sorry if that's sad news for anyone, and I apologize if this breaks someone's workflow someday. I don't think this plugin will stop working anytime soon, but if it does... 😬 

Probably the biggest risk in this breaking is a breaking change to Telescope.

**Comment by NTBBloodbath** [comment]
Hey, hope you're doing well too!

I really love the work you've done with zf, I've been following the project for a while now and would like to help keep this integration to telescope functional. What would need to be done when maintaining the plugin? I don't know if there is something besides updating the zf libraries every time a new version is available if required, keeping the plugin functional and addressing issues/PRs :p

**Comment by natecraddock** [comment]
Hi @NTBBloodbath thanks for being willing!

This really wouldn't be that much work. I'm willing to update the libraries whenever I update zf (really simple, just run the justfile and do a quick test in nvim). I worry more about nvim/telescope compatibility in the future if APIs change.

I imagine that I would just give you contributor access to this repo and then both of us could maintain it. It would just give me some peace-of-mind that a neovim user has access to fix things, address issues/PRs.

So if you are still willing, let me know and I'll add you as a contributor!

**Comment by natecraddock** [comment]
Thanks! I just added you as a collaborator. Thanks again for being willing to help! It takes some pressure off me :)

**Comment by NTBBloodbath** [comment]
Glad to help maintaining this amazing integration :p

I'm going to accept the invitation as soon as GitHub starts working properly again (seems like there are a lot of issues right now, you can check out [GitHub status site](https://githubstatus.com))!

**Comment by natecraddock** [comment]
Yeah I noticed it was down and snuck in between some downtime to comment. Hope they get it figured out soon!

**Comment by NTBBloodbath** [comment]
It seems like everything is working again, already accepted the invitation! :p
